#!/usr/bin/env node

var subManager = require('./subManager.js')();
var version = require('./package.json').version;

var usage = function () {
    console.log(
        "git-sub v" + version + "\n" +
        "USAGE: git-sub update\n" +
        "       git-sub status\n" +
        "       git-sub checkout\n" +
        "       git-sub pull\n" +
        "       git-sub clear \<-f\>  [CAREFUL : This option's command has \"git reset --hard && git clean -f -d .\"\n" +
        "       git-sub link \<-f\>   [CAREFUL : This option's command has \"git push origin <branch>\"\n" +
        "       git-sub npm install\n" +
        "       git-sub npm list\n"
    );
};


switch (process.argv[2]) {
    case 'status':
    case 'checkout':
    case 'pull':
    case 'update':
        if (process.argv.length === 3) {
            subManager[process.argv[2]]();
        } else {
            usage();
        }
        break;

    case 'clear':
    case 'link':
        if (process.argv.length === 4 && process.argv[3] === '-f') {
            subManager[process.argv[2]]();
        } else {
            usage();
        }
        break;

    case 'npm':
        if (process.argv.length === 4) {
            switch (process.argv[3]) {
                case "install" :
                case "list":
                    subManager[process.argv[2] + "_" + process.argv[3]]();
                    break;
                default:
                    usage();
                    break;
            }
        } else {
            usage();
        }
        break;

    default:
        usage();
        break;
}
